/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import arsmagica.ArsMagica;
import java.io.File;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;


/**
 *
 * @author Chaha
 */
public class AdminScreen extends javax.swing.JFrame {
    public ArsMagica main;
    public Document editedDoc;
    
    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
    }
    
    public void createXML(){
        
    }
    
    public void saveXML(){
        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        Transformer transformer;
        try {
            transformer = transformerFactory.newTransformer();
            DOMSource xmlSource = new DOMSource(editedDoc);
            StreamResult outputTarget = new StreamResult(new File("gameData.xml"));
            transformer.transform(xmlSource, outputTarget);
        } catch (TransformerException ex) {
            ex.printStackTrace();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        covenantStrengthButtonGroup = new javax.swing.ButtonGroup();
        covenantTypeButtonGroup = new javax.swing.ButtonGroup();
        virtueViceStrengthButtonGroup = new javax.swing.ButtonGroup();
        virtueViceTypeButtonGroup = new javax.swing.ButtonGroup();
        adnminTabs = new javax.swing.JTabbedPane();
        covenantOptionPanel = new javax.swing.JPanel();
        covenantOptionNameLabel = new javax.swing.JLabel();
        covenantOptionName = new javax.swing.JTextField();
        majorRadioButton = new javax.swing.JRadioButton();
        minorRadioButton = new javax.swing.JRadioButton();
        boonRadioButton = new javax.swing.JRadioButton();
        hookRadioButton = new javax.swing.JRadioButton();
        neutralRadioButton = new javax.swing.JRadioButton();
        validateCovenantOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CovOptList = new javax.swing.JList<>();
        covOptModif = new javax.swing.JButton();
        covOptClear = new javax.swing.JButton();
        virtuesVicesPanel = new javax.swing.JPanel();
        virtueViceNameLabel = new javax.swing.JLabel();
        virtueViceNameField = new javax.swing.JTextField();
        virtueViceMajorRadio = new javax.swing.JRadioButton();
        virtueViceMinorRadio = new javax.swing.JRadioButton();
        virtueViceNeutralRadio = new javax.swing.JRadioButton();
        virtueRadio = new javax.swing.JRadioButton();
        viceRadio = new javax.swing.JRadioButton();
        validateVirtueVice = new javax.swing.JButton();
        eventsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");

        covenantOptionNameLabel.setText("Nom");

        covenantStrengthButtonGroup.add(majorRadioButton);
        majorRadioButton.setText("Majeur");

        covenantStrengthButtonGroup.add(minorRadioButton);
        minorRadioButton.setSelected(true);
        minorRadioButton.setText("Mineur");
        minorRadioButton.setToolTipText("");

        covenantTypeButtonGroup.add(boonRadioButton);
        boonRadioButton.setSelected(true);
        boonRadioButton.setText("Avantage");

        covenantTypeButtonGroup.add(hookRadioButton);
        hookRadioButton.setText("Accroche");

        covenantStrengthButtonGroup.add(neutralRadioButton);
        neutralRadioButton.setText("Neutre");
        neutralRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neutralRadioButtonActionPerformed(evt);
            }
        });

        validateCovenantOption.setText("Créer");
        validateCovenantOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateCovenantOptionActionPerformed(evt);
            }
        });

        CovOptList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(CovOptList);

        covOptModif.setText("Modifier");

        covOptClear.setText("Vider");

        javax.swing.GroupLayout covenantOptionPanelLayout = new javax.swing.GroupLayout(covenantOptionPanel);
        covenantOptionPanel.setLayout(covenantOptionPanelLayout);
        covenantOptionPanelLayout.setHorizontalGroup(
            covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                        .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neutralRadioButton)
                            .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                                .addComponent(covenantOptionNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(covenantOptionName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                                .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(majorRadioButton)
                                    .addComponent(minorRadioButton))
                                .addGap(86, 86, 86)
                                .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hookRadioButton)
                                    .addComponent(boonRadioButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(covOptClear)
                        .addGap(18, 18, 18)
                        .addComponent(covOptModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validateCovenantOption)))
                .addContainerGap())
        );
        covenantOptionPanelLayout.setVerticalGroup(
            covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(covenantOptionPanelLayout.createSequentialGroup()
                        .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(covenantOptionNameLabel)
                            .addComponent(covenantOptionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(majorRadioButton)
                            .addComponent(boonRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minorRadioButton)
                            .addComponent(hookRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(neutralRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(covenantOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validateCovenantOption)
                    .addComponent(covOptModif)
                    .addComponent(covOptClear))
                .addContainerGap())
        );

        adnminTabs.addTab("Options d'Alliance", covenantOptionPanel);

        virtueViceNameLabel.setText("Nom");

        virtueViceStrengthButtonGroup.add(virtueViceMajorRadio);
        virtueViceMajorRadio.setText("Majeur");

        virtueViceStrengthButtonGroup.add(virtueViceMinorRadio);
        virtueViceMinorRadio.setSelected(true);
        virtueViceMinorRadio.setText("Mineur");

        virtueViceStrengthButtonGroup.add(virtueViceNeutralRadio);
        virtueViceNeutralRadio.setText("Neutre");

        virtueViceTypeButtonGroup.add(virtueRadio);
        virtueRadio.setSelected(true);
        virtueRadio.setText("Vertu");

        virtueViceTypeButtonGroup.add(viceRadio);
        viceRadio.setText("Vice");

        validateVirtueVice.setText("Créer");

        javax.swing.GroupLayout virtuesVicesPanelLayout = new javax.swing.GroupLayout(virtuesVicesPanel);
        virtuesVicesPanel.setLayout(virtuesVicesPanelLayout);
        virtuesVicesPanelLayout.setHorizontalGroup(
            virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                        .addComponent(virtueViceMajorRadio)
                        .addGap(68, 68, 68)
                        .addComponent(virtueRadio))
                    .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                        .addComponent(virtueViceNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(virtueViceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                        .addGroup(virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(virtueViceNeutralRadio)
                            .addComponent(virtueViceMinorRadio))
                        .addGap(68, 68, 68)
                        .addComponent(viceRadio)))
                .addContainerGap(851, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, virtuesVicesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validateVirtueVice)
                .addContainerGap())
        );
        virtuesVicesPanelLayout.setVerticalGroup(
            virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(virtueViceNameLabel)
                    .addComponent(virtueViceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(virtueViceMajorRadio)
                    .addComponent(virtueRadio))
                .addGroup(virtuesVicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(virtueViceMinorRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(virtueViceNeutralRadio))
                    .addGroup(virtuesVicesPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(viceRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(validateVirtueVice)
                .addContainerGap())
        );

        adnminTabs.addTab("Vertus et Vices", virtuesVicesPanel);

        javax.swing.GroupLayout eventsPanelLayout = new javax.swing.GroupLayout(eventsPanel);
        eventsPanel.setLayout(eventsPanelLayout);
        eventsPanelLayout.setHorizontalGroup(
            eventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        eventsPanelLayout.setVerticalGroup(
            eventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        adnminTabs.addTab("Evèvements", eventsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adnminTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adnminTabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void neutralRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neutralRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neutralRadioButtonActionPerformed

    private void validateCovenantOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateCovenantOptionActionPerformed
        NodeList categories = editedDoc.getFirstChild().getChildNodes();
        for(int i = 0; i<categories.getLength();i++){
            Node category = categories.item(i);
            if(category.getNodeName().equals("CovenantOption")){
                Element covOpt = editedDoc.createElement(covenantOptionName.getText());
                if(minorRadioButton.isSelected()){
                    covOpt.setAttribute("cost", "Minor");
                }else if (majorRadioButton.isSelected()){
                    covOpt.setAttribute("cost", "Major");
                }else {covOpt.setAttribute("cost", "Neutral");}
                if(boonRadioButton.isSelected()){
                    covOpt.setAttribute("type", "Boon");
                }else {covOpt.setAttribute("type", "Hook");}
                category.appendChild(covOpt);
                break;
            }
        }
    }//GEN-LAST:event_validateCovenantOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> CovOptList;
    private javax.swing.JTabbedPane adnminTabs;
    private javax.swing.JRadioButton boonRadioButton;
    private javax.swing.JButton covOptClear;
    private javax.swing.JButton covOptModif;
    private javax.swing.JTextField covenantOptionName;
    private javax.swing.JLabel covenantOptionNameLabel;
    private javax.swing.JPanel covenantOptionPanel;
    private javax.swing.ButtonGroup covenantStrengthButtonGroup;
    private javax.swing.ButtonGroup covenantTypeButtonGroup;
    private javax.swing.JPanel eventsPanel;
    private javax.swing.JRadioButton hookRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton majorRadioButton;
    private javax.swing.JRadioButton minorRadioButton;
    private javax.swing.JRadioButton neutralRadioButton;
    private javax.swing.JButton validateCovenantOption;
    private javax.swing.JButton validateVirtueVice;
    private javax.swing.JRadioButton viceRadio;
    private javax.swing.JRadioButton virtueRadio;
    private javax.swing.JRadioButton virtueViceMajorRadio;
    private javax.swing.JRadioButton virtueViceMinorRadio;
    private javax.swing.JTextField virtueViceNameField;
    private javax.swing.JLabel virtueViceNameLabel;
    private javax.swing.JRadioButton virtueViceNeutralRadio;
    private javax.swing.ButtonGroup virtueViceStrengthButtonGroup;
    private javax.swing.ButtonGroup virtueViceTypeButtonGroup;
    private javax.swing.JPanel virtuesVicesPanel;
    // End of variables declaration//GEN-END:variables
}
