/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsmagica.gui;

import java.awt.Component;
import arsmagica.model.AM;
import arsmagica.model.Ability;
import arsmagica.model.AnyCharacter;
import arsmagica.model.GameData;
import arsmagica.model.MageCharacter;

/**
 *
 * @author Chaha
 */
public class CharacterSetup extends javax.swing.JFrame {
    GameData model;
    SetupScreen setupScreen;
    
    /**
     * Creates new form CharacterSetup
     */
    public CharacterSetup(GameData model, SetupScreen setupScreen) {
        this.model = model;
        this.setupScreen = setupScreen;
        initComponents();
        for(AM.House h : AM.House.values()){
            houseComboBox.addItem(h.toString());
        }
        for(Component c : apprenticeshipSetup.getComponents()){
                c.setEnabled(false);
        }
    }

    // appelée lorsqu'on crée un nouveau personnage, vide les champs de l'écran de création
    public void clean (){
        // TO DO
    }
    
    // appelée lorsqu'on veut modifier un personnage, affiche ses valeurs dans l'écran de création
    public void fillCharSetup(AnyCharacter charac){
        //TO DO
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        namesIdeasButton = new javax.swing.JButton();
        mageBox = new javax.swing.JCheckBox();
        validateButton = new javax.swing.JButton();
        childhoodSetup = new javax.swing.JPanel();
        childhoodLabel = new javax.swing.JLabel();
        giftedOrNot = new javax.swing.JCheckBox();
        apprenticeshipSetup = new javax.swing.JPanel();
        apprenticeshipLabel = new javax.swing.JLabel();
        houseComboBox = new javax.swing.JComboBox<>();
        virtuesVicesSetup = new javax.swing.JPanel();
        virtuesVicesLabel = new javax.swing.JLabel();
        lifeSetup = new javax.swing.JPanel();
        ageLabel = new javax.swing.JLabel();
        ageValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création de personnage");

        nameField.setText("Nom");

        namesIdeasButton.setText("Idées");

        mageBox.setText("Mage");
        mageBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mageBoxStateChanged(evt);
            }
        });

        validateButton.setText("Créer le personnage");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        childhoodSetup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        childhoodLabel.setText("Enfance");

        javax.swing.GroupLayout childhoodSetupLayout = new javax.swing.GroupLayout(childhoodSetup);
        childhoodSetup.setLayout(childhoodSetupLayout);
        childhoodSetupLayout.setHorizontalGroup(
            childhoodSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childhoodSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(childhoodLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        childhoodSetupLayout.setVerticalGroup(
            childhoodSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childhoodSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(childhoodLabel)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        giftedOrNot.setText("Le Don ?");

        apprenticeshipSetup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        apprenticeshipLabel.setText("Apprentissage");

        javax.swing.GroupLayout apprenticeshipSetupLayout = new javax.swing.GroupLayout(apprenticeshipSetup);
        apprenticeshipSetup.setLayout(apprenticeshipSetupLayout);
        apprenticeshipSetupLayout.setHorizontalGroup(
            apprenticeshipSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apprenticeshipSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apprenticeshipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(houseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        apprenticeshipSetupLayout.setVerticalGroup(
            apprenticeshipSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apprenticeshipSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apprenticeshipSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apprenticeshipLabel)
                    .addComponent(houseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        virtuesVicesSetup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        virtuesVicesLabel.setText("Vertus et Vices");

        javax.swing.GroupLayout virtuesVicesSetupLayout = new javax.swing.GroupLayout(virtuesVicesSetup);
        virtuesVicesSetup.setLayout(virtuesVicesSetupLayout);
        virtuesVicesSetupLayout.setHorizontalGroup(
            virtuesVicesSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuesVicesSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(virtuesVicesLabel)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        virtuesVicesSetupLayout.setVerticalGroup(
            virtuesVicesSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuesVicesSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(virtuesVicesLabel)
                .addContainerGap(555, Short.MAX_VALUE))
        );

        lifeSetup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout lifeSetupLayout = new javax.swing.GroupLayout(lifeSetup);
        lifeSetup.setLayout(lifeSetupLayout);
        lifeSetupLayout.setHorizontalGroup(
            lifeSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        lifeSetupLayout.setVerticalGroup(
            lifeSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ageLabel.setText("Âge :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giftedOrNot)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mageBox)
                                        .addGap(178, 178, 178)
                                        .addComponent(ageLabel))
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ageValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addComponent(namesIdeasButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apprenticeshipSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(childhoodSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addComponent(lifeSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(validateButton)
                    .addComponent(virtuesVicesSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namesIdeasButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mageBox)
                                .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(childhoodSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(giftedOrNot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apprenticeshipSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(virtuesVicesSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(validateButton))
                    .addComponent(lifeSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        AnyCharacter charac;
        if(mageBox.isSelected()){
            charac = new MageCharacter();
            ((MageCharacter)charac).house = AM.House.enumOfString((String)houseComboBox.getSelectedItem());
            // and the rest
        } else {charac = new AnyCharacter();}
        charac.name = nameField.getText();
        model.characters.characters.put(charac.name,charac);
        model.characters.addElement(charac.name);
        
        
        // and the rest
        this.setVisible(false);
        setupScreen.setVisible(true);
    }//GEN-LAST:event_validateButtonActionPerformed

    // Lorsque la case mage est cochée ou décochée
    private void mageBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mageBoxStateChanged
        if(mageBox.isSelected()){
            giftedOrNot.doClick();
            giftedOrNot.setEnabled(false);
            for(Component c : apprenticeshipSetup.getComponents()){
                c.setEnabled(true);
            }
        }
        else{
            giftedOrNot.setEnabled(true);
            for(Component c : apprenticeshipSetup.getComponents()){
                c.setEnabled(false);
            }
        }
    }//GEN-LAST:event_mageBoxStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CharacterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CharacterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CharacterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CharacterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CharacterSetup().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageValueLabel;
    private javax.swing.JLabel apprenticeshipLabel;
    private javax.swing.JPanel apprenticeshipSetup;
    private javax.swing.JLabel childhoodLabel;
    private javax.swing.JPanel childhoodSetup;
    private javax.swing.JCheckBox giftedOrNot;
    private javax.swing.JComboBox<String> houseComboBox;
    private javax.swing.JPanel lifeSetup;
    private javax.swing.JCheckBox mageBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton namesIdeasButton;
    private javax.swing.JButton validateButton;
    private javax.swing.JLabel virtuesVicesLabel;
    private javax.swing.JPanel virtuesVicesSetup;
    // End of variables declaration//GEN-END:variables
}
