/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsmagica.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author Admin
 */
public class InDialog extends javax.swing.JPanel {

    Image img;
    JTextArea dialText;
    ArrayList<JButton> buttons;
    
    /**
     * Creates new form InDialog
     */
    public InDialog(String text) {
        initComponents();
        //usableSpace.setMaximumSize(new Dimension(((int) Math.floor(this.getSize().height*0.8)),this.getSize().width));
        this.dialText = new JTextArea(text);
        dialText.setOpaque(false);
        
        usableSpace.add(dialText);
        try{
            img=ImageIO.read(new File("resources/parchment.jpeg"));
        }catch(Exception e){
            
        }
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
            g.drawImage(img, 0,0, this.getWidth(),this.getHeight(), this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usableSpace = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), null));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        usableSpace.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        usableSpace.setMinimumSize(new java.awt.Dimension(100, 100));
        usableSpace.setName(""); // NOI18N
        usableSpace.setOpaque(false);
        usableSpace.setLayout(new java.awt.BorderLayout());
        add(usableSpace);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel usableSpace;
    // End of variables declaration//GEN-END:variables
}
