/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsmagica.gui;

import arsmagica.model.AnyCharacter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import arsmagica.model.GameData;
import arsmagica.model.MageCharacter;

/**
 *
 * @author Chaha
 */
public class SetupScreen extends javax.swing.JFrame implements ListSelectionListener {
    GameData model;
    CharacterSetup charSetup;
    CovenantSetup covSetup;
    
    /**
     * Creates new form SetupScreen
     * @param model
     */
    public SetupScreen(GameData model) {
        this.model = model;
        initComponents();
        modifyCharacter.setEnabled(false);
        deleteCharacter.setEnabled(false);
        charactersList.setModel(model.characters);
    }

    private void covenantSetup(){
        if(model.covenant == null){
            covSetup = new CovenantSetup(model, this);
        }
        this.setVisible(false);
        covSetup.setVisible(true);
    }
    
    private void createCharacter(){
        AnyCharacter charac = new AnyCharacter();
        if (charSetup == null){
            charSetup = new CharacterSetup(model, this);
        } else {
            charSetup.clean();
        }
        this.setVisible(false);
        charSetup.setVisible(true);
    }

    
    // Quand un changement a lieu dans la sélection de personnage
    @Override
    public void valueChanged(ListSelectionEvent e) {
        AnyCharacter selectedCharacter;
        if (e.getValueIsAdjusting() == false) {
 
            if (charactersList.getSelectedIndex() == -1) {
            //No selection: disable delete, up, and down buttons.
                deleteCharacter.setEnabled(false);
                modifyCharacter.setEnabled(false);
                characterView.setVisible(false);
 
            } else {
                selectedCharacter = model.characters.characters.get(charactersList.getSelectedValue());
                displayCharacter(selectedCharacter);
                characterView.setVisible(true);
                modifyCharacter.setEnabled(true);
                deleteCharacter.setEnabled(true);
            }
        }
    }
    
    // montrer les informations du personnage sélectionné dans le cadre d'aperçu
    public void displayCharacter(AnyCharacter selectedCharacter){
        characterViewName.setText(selectedCharacter.name);
        if(selectedCharacter.isMage()){
            characterViewHouse.setText(((MageCharacter)selectedCharacter).house.toString());
        }else {
            
        }
    }
    
    public void displayCovenant(){
        covenantViewName.setText(model.covenant.name);
        covenantViewTribunal.setText(model.covenant.tribunal.toString());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCharacter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        charactersList = new javax.swing.JList<>();
        deleteCharacter = new javax.swing.JButton();
        characterView = new javax.swing.JPanel();
        characterName = new javax.swing.JLabel();
        innerCharacterViewPanel = new javax.swing.JPanel();
        characterViewName = new javax.swing.JLabel();
        characterViewHouse = new javax.swing.JLabel();
        characterViewSocialStatus = new javax.swing.JLabel();
        covenantView = new javax.swing.JPanel();
        covenantName = new javax.swing.JLabel();
        innerCovenantViewPanel = new javax.swing.JPanel();
        covenantViewName = new javax.swing.JLabel();
        covenantViewTribunal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        creationStatus = new javax.swing.JTextArea();
        modifyCharacter = new javax.swing.JButton();
        beginGameButton = new javax.swing.JButton();
        changeCovenantButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecran de Creation");

        createCharacter.setText("Créer Personnage");
        createCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCharacterActionPerformed(evt);
            }
        });

        charactersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(charactersList);

        deleteCharacter.setText("Retirer Personnage");
        deleteCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCharacterActionPerformed(evt);
            }
        });

        characterView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        characterName.setText("Nom du personnage");

        characterViewName.setText("Nom");

        characterViewHouse.setText("Maison");

        characterViewSocialStatus.setText("Statut social");

        javax.swing.GroupLayout innerCharacterViewPanelLayout = new javax.swing.GroupLayout(innerCharacterViewPanel);
        innerCharacterViewPanel.setLayout(innerCharacterViewPanelLayout);
        innerCharacterViewPanelLayout.setHorizontalGroup(
            innerCharacterViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCharacterViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerCharacterViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterViewName)
                    .addComponent(characterViewHouse)
                    .addComponent(characterViewSocialStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innerCharacterViewPanelLayout.setVerticalGroup(
            innerCharacterViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCharacterViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterViewName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(characterViewHouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(characterViewSocialStatus)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout characterViewLayout = new javax.swing.GroupLayout(characterView);
        characterView.setLayout(characterViewLayout);
        characterViewLayout.setHorizontalGroup(
            characterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, characterViewLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(characterName)
                .addGap(156, 156, 156))
            .addGroup(characterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerCharacterViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        characterViewLayout.setVerticalGroup(
            characterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(characterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(innerCharacterViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        covenantView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        covenantName.setText("Alliance");

        covenantViewName.setText("Nom");

        covenantViewTribunal.setText("Tribunal");

        javax.swing.GroupLayout innerCovenantViewPanelLayout = new javax.swing.GroupLayout(innerCovenantViewPanel);
        innerCovenantViewPanel.setLayout(innerCovenantViewPanelLayout);
        innerCovenantViewPanelLayout.setHorizontalGroup(
            innerCovenantViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCovenantViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerCovenantViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(covenantViewName)
                    .addComponent(covenantViewTribunal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innerCovenantViewPanelLayout.setVerticalGroup(
            innerCovenantViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCovenantViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(covenantViewName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(covenantViewTribunal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout covenantViewLayout = new javax.swing.GroupLayout(covenantView);
        covenantView.setLayout(covenantViewLayout);
        covenantViewLayout.setHorizontalGroup(
            covenantViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covenantViewLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(covenantName)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(covenantViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerCovenantViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        covenantViewLayout.setVerticalGroup(
            covenantViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covenantViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(covenantName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(innerCovenantViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        creationStatus.setColumns(20);
        creationStatus.setRows(5);
        creationStatus.setText("Manques et problèmes");
        jScrollPane2.setViewportView(creationStatus);

        modifyCharacter.setText("Modifier Personnage");
        modifyCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCharacterActionPerformed(evt);
            }
        });

        beginGameButton.setText("Commencer la partie");

        changeCovenantButton.setText("Changer l'Alliance");
        changeCovenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCovenantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(createCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifyCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeCovenantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(covenantView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifyCharacter)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(characterView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(covenantView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beginGameButton)
                            .addComponent(changeCovenantButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCharacterActionPerformed
        createCharacter();
    }//GEN-LAST:event_createCharacterActionPerformed

    private void deleteCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCharacterActionPerformed
        model.characters.characters.remove(charactersList.getSelectedValue());
    }//GEN-LAST:event_deleteCharacterActionPerformed

    private void modifyCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCharacterActionPerformed
        charSetup.fillCharSetup(model.characters.characters.get(charactersList.getSelectedValue()));
        this.setVisible(false);
        charSetup.setVisible(true);
    }//GEN-LAST:event_modifyCharacterActionPerformed

    private void changeCovenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCovenantButtonActionPerformed
        covenantSetup();
    }//GEN-LAST:event_changeCovenantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SetupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SetupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SetupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SetupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SetupScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginGameButton;
    private javax.swing.JButton changeCovenantButton;
    private javax.swing.JLabel characterName;
    private javax.swing.JPanel characterView;
    private javax.swing.JLabel characterViewHouse;
    private javax.swing.JLabel characterViewName;
    private javax.swing.JLabel characterViewSocialStatus;
    private javax.swing.JList<String> charactersList;
    private javax.swing.JLabel covenantName;
    private javax.swing.JPanel covenantView;
    private javax.swing.JLabel covenantViewName;
    private javax.swing.JLabel covenantViewTribunal;
    private javax.swing.JButton createCharacter;
    private javax.swing.JTextArea creationStatus;
    private javax.swing.JButton deleteCharacter;
    private javax.swing.JPanel innerCharacterViewPanel;
    private javax.swing.JPanel innerCovenantViewPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyCharacter;
    // End of variables declaration//GEN-END:variables
}
